# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bhtsne = function(X, no_dims=2, perplexity=30, theta=0.5) {
    .Call('bh_sne',
          N = nrow(X),
          D = ncol(X),
          no_dims = no_dims, 
          perplexity = perplexity, 
          theta = theta, 
          PACKAGE = 'bhtsneR'
    )
}

